name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build test image
        run: docker build --tag todo-app:test --target test .

      - name: Run tests
        run: docker run todo-app:test
