name: Continuous Integration
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'ansible/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'ansible/**'

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build test image
        run: docker build --tag todo-app:test --target test .

      - name: Run tests
        run: docker run todo-app:test
  container_build_and_push:
    name: Container build and push
    needs: build_and_test
    if: github.event_name == 'push' && endsWith(github.ref, 'module9') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run echo statement
        run: echo Publishing!

